# https://pnpm.io/supply-chain-security 

onlyBuiltDependencies:
  - esbuild
  - sharp
blockExoticSubdeps: true
minimumReleaseAge: 4320 # 3日
trustPolicy: no-downgrade
trustPolicyIgnoreAfter: 144000 # 100日
engineStrict: true
