name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  release:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Setup pnpm
        uses: pnpm/action-setup@0977fd99725f1db4007ccb2928dbb4e90d06cc86 # v6.0.10
        with:
          run_install: true
          cache: true

      - name: チェック
        run: pnpm check

      - name: URL生成
        id: generate_url
        run: |
          git fetch --tags -f
          PREVIOUS_TAG=$(git tag | sort -V --reverse | sed -n 2p)
          echo "一つ前のタグ: $PREVIOUS_TAG"
          if [ -n "$PREVIOUS_TAG" ]; then
              echo "url=https://github.com/${{ github.repository }}/compare/$PREVIOUS_TAG...${{ github.ref_name }}" >> $GITHUB_OUTPUT
          else
              echo "url=https://github.com/${{ github.repository }}/commits/${{ github.ref_name }}" >> $GITHUB_OUTPUT
          fi

      - name: ビルド
        run: pnpm zip

      - name: リリース作成
        uses: softprops/action-gh-release@3d0d9888cb7fd7b750713d6e236d1fcb99157228 # v3.0.2
        with:
          files: .output/firefox.xpi
          name: ${{ github.ref_name }}
          tag_name: ${{ github.ref_name }}
          body: |
            **Full Changelog**: ${{ steps.generate_url.outputs.url }}

      - name: ストアに提出
        run: |
          pnpm wxt submit \
          --firefox-zip .output/firefox.xpi \
          --firefox-sources-zip .output/*-sources.zip
        env:
          FIREFOX_EXTENSION_ID: ${{ secrets.FIREFOX_EXTENSION_ID }}
          FIREFOX_JWT_ISSUER: ${{ secrets.FIREFOX_JWT_ISSUER }}
          FIREFOX_JWT_SECRET: ${{ secrets.FIREFOX_JWT_SECRET }}
