name: release

on:
    push:
        tags:
            - "v*"

permissions:
    contents: write

jobs:
    release:
        runs-on: ubuntu-latest

        steps:
            - uses: nines75/composite-action/setup-pnpm@main

            - name: URL生成
              run: |
                  git fetch --tags -f
                  PREVIOUS_TAG=$(git tag | sort -V --reverse | sed -n 2p)
                  echo "一つ前のタグ: $PREVIOUS_TAG"
                  if [ -n "$PREVIOUS_TAG" ]; then
                      echo "URL=https://github.com/${{ github.repository }}/compare/$PREVIOUS_TAG...${{ github.ref_name }}" >> $GITHUB_ENV
                  else
                      echo "URL=https://github.com/${{ github.repository }}/commits/${{ github.ref_name }}" >> $GITHUB_ENV
                  fi

            - name: ビルド
              run: pnpm zip

            - name: リリース作成
              uses: softprops/action-gh-release@v2
              with:
                  files: .output/firefox.xpi
                  name: ${{ github.ref_name }}
                  tag_name: ${{ github.ref_name }}
                  body: |
                      **Full Changelog**: ${{ env.URL }}
